require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.5
  NewCops: enable
  Exclude:
    - db/**/*
    - bin/**/*
    - target/**/*
Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Rails/FilePath:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
